import { ID } from "./model";

export type ICommonKADSForm = any;

export type ICommonKADSLibrary = {
    forms: ICommonKADSForm[]
};

export type IFilePath = string;

// IN
export type IChenModelFile = IFilePath;
export type ICollectionsFile = IFilePath;

// OUT
export type IJsonFile = IFilePath;
export type IYamlFile = IFilePath;

export type ISematicNetworkFile = IJsonFile;
export type IFramesBookFile = IYamlFile;

export type IAppBundleFile = IFilePath;

export type SourceFilesDirectory = IFilePath;

export type AppDirectory = {

    id: ID;

    /**
     * Storage root folder for everything generated by AS Seed 
     */
    baseFolder: IFilePath;

    /**
     * Application settings and enviroment properties directory
     */
    configFolder?: IFilePath;

    /**
     * Directory with chen-like schema files to be imported
     */
    chensFolder?: IFilePath;

    /**
     * Directory with non-sql collection schema files to be imported
     */
    collectionsFolder?: IFilePath;

    /**
     * Directory with sql or non-sql anotated data ocurrences
     */
    dataFolder?: IFilePath;

    /**
     * Final Output directory for exchanging data with AS Framework
     */
    appFolder?: IFilePath;

    /**
     * Contains relation table with compressed tree (branches are segments of fk)
     */
    treeFolder?: IFilePath;

    /**
     * Contains tmp data for AS SDK BIM Navigator searches resultsnavigationFolder
     */
    navigationFolder?: IFilePath;

};